### ISSUE TITLE
Switch to using git tag based build (once LFS issues are resolved)

### ISSUE THREAD

**Issue by hhyyrylainen** [flathub/com.revolutionarygamesstudio.ThriveLauncher#12]
currently tar file download is used as a workaround

Change required to the build yaml:
```yaml
      - type: git
        url: https://github.com/Revolutionary-Games/Thrive-Launcher.git
        tag: "v2.0.2"
```
